name: Daily Commit Workflow

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Git configuration (username and email)
      - name: Set Git username and email
        run: |
          git config --global user.name "DevSync Automation"
          git config --global user.email "22f3002631@ds.study.iitm.ac.in"

      # Step 3: Make a change in the repository (e.g., update a README file)
      - name: Update README or add a status file
        run: |
          echo "Update performed by DevSync automation at $(date)" >> README.md
          git add README.md
          git commit -m "Automated commit by DevSync automation at $(date)"
          
      # Step 4: Push the changes back to the repository
      - name: Push changes
        run: |
          git push origin main  # Adjust the branch name as needed (e.g., 'main' or 'master')
