name: Daily Commit Update

on:
  schedule:
    # This cron expression schedules the workflow to run once per day at 9:00 AM UTC
    - cron: '0 9 * * *'

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Git configuration for commits
      - name: Set up Git user
        run: |
          git config --global user.name 'DevSync Automation'
          git config --global user.email '22f3002631@ds.study.iitm.ac.in'

      # Create a commit to update the repository
      - name: Make daily commit with update
        run: |
          # Create a dummy change or update a specific file, for example, updating a README or status file
          echo "Daily update: $(date)" >> update_log.txt
          git add update_log.txt
          git commit -m "Daily commit update $(date)"
          git push

      # Ensure the commit is tracked
      - name: Push changes to the repository
        run: git push
