name: Daily Commit Workflow

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Git configuration (username and email)
      - name: Set Git username and email
        run: |
          git config --global user.name "DevSync Automation"
          git config --global user.email "22f3002631@ds.study.iitm.ac.in"

      # Step 3: Create a dummy change or update a specific file (e.g., update a status file)
      - name: Update status or add log file
        run: |
          echo "Daily commit update $(date)" > update_log.txt
          git add update_log.txt
          git commit -m "Daily commit update $(date)"

      # Step 4: Push changes using the GitHub Token for authentication
      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
